[package]
name = "day24"
version = "0.1.0"
authors = ["Neil Gall <neil@gall.scot>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parser = { path = "../parser" }
strum = "0.20.0"
strum_macros = "0.20.0"
